version: '2.2'
services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8301:8301/udp"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command:
      - agent
    networks:
      - ssabae-release
    volumes:
      - ./config:/consul/config
      - ./data:/consul/data
    restart: always

networks:
  ssabae-release:
    name: ssabae-release
    driver: bridge
