version: '3.7'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - ssabae-release
    hostname: {{ inventory_hostname }}

networks:
  ssabae-release:
    name: ssabae-release
    driver: bridge
